### ISSUE TITLE
update ClojureBridge description at clojurebridge.org

### ISSUE THREAD

**Issue by davidchambers** [ClojureBridge/organizing#29]
@mtrimpe, in a recent post to the ClojureBridge Workshops mailing list:

> What *is* the desired focus and approach of ClojureBridge with regards to different aspects of diversity? And whatever its; can we bring the messaging about that in line across the board?

The responses from @seancorfield and @yokolet suggest that the ClojureBridge mission is to increase diversity—including but not limited to gender diversity—in the Clojure community. Women are one of several underrepresented groups for which a workshop could be organized.

We should update the description on the [website][1] to reflect this position.

Current description:

> ClojureBridge aims to increase diversity within the Clojure community by offering free, beginner-friendly Clojure programming workshops for women.

Proposed description:

> ClojureBridge aims to increase diversity within the Clojure community by offering free, beginner-friendly Clojure programming workshops for women and for other underrepresented groups.

This could be accompanied by something along these lines:

> Early workshops focused on the largest underrepresented group in the Clojure community: women. Organizers are free to choose a different underrepresented group when planning a workshop. A workshop's description should state the group or groups for which the workshop is to be held.

Please suggest improvements to these two paragraphs, or completely different ways to phrase this. :)

[1]: http://www.clojurebridge.org

**Comment by kpfell** [comment]
> ClojureBridge aims to increase diversity within the Clojure community by offering free, beginner-friendly Clojure programming workshops for women and for other underrepresented groups.

I feel weird about the phrasing of "for women and for other underrepresented groups."

In particular: If we're going to expand the site copy to refer to people who aren't necessarily women, I feel like the site should just say "for underrepresented groups in tech," as women should not continue to be elevated as a special group with its own byline.

> Early workshops focused on the largest underrepresented group in the Clojure community: women. Organizers are free to choose a different underrepresented group when planning a workshop. A workshop's description should state the group or groups for which the workshop is to be held.

I feel weird about saying "largest underrepresented group in the Clojure community"--perhaps just "Early workshops focused on women," which is technically accurate and probably the only thing that needs to be said right now? It would also be worth further clarifying our potential stance on hosting workshops for people who aren't women: that we don't really know how to organize those workshops right now and have not historically done so, but we're working on it? ¯\_(ツ)_/¯

**Comment by davidchambers** [comment]
Both your suggested changes sound good to me, @kpfell. I opened this issue for discussion without a strong opinion. I'm happy to submit a pull request with the updated description if others agree.

**Comment by yokolet** [comment]
I updated both clojurebrige.org and REAME.md of this repo. Now, "for women" is replaced by "underrepresented groups." Please check.

**Comment by k4y3ff** [comment]
I'm 👍 on your changes, @yokolet!

I'll leave @davidchambers to close the issue, though, since he opened this thread. 🙂

**Comment by davidchambers** [comment]
Thank you, @yokolet. :)
