### ISSUE TITLE
anarchival link not working

### ISSUE THREAD

**Issue by daveliepmann** [ClojureBridge/organizing#32]
The link to "[moving through a hierarchical system](http://anarchival.net/Strange-Loop/)" by Amber Adams on [Resources on Diversity](https://github.com/ClojureBridge/organizing/blob/master/Resources-on-Diversity.md) appears to be dead. The domain appears to have lapsed. I do not see an alternate URL.

**Comment by davidchambers** [comment]
That's a shame. I do not see the slides or transcript in the [StrangeLoop2014][1] repository, nor do I see the post on Google when doing an exact-match search for "moving through a hierarchical system".

Does anyone here know Amber Adams? If so you could contact Amber to see whether this content could be made accessible again somehow.


[1]: https://github.com/strangeloop/StrangeLoop2014

**Comment by daveliepmann** [comment]
https://twitter.com/anarchival

**Comment by puredanger** [comment]
This was a writeup about the conference afterwards, not a talk. Wayback machine archive has it:

https://web.archive.org/web/20150202220502/http://anarchival.net/Strange-Loop/

**Comment by yokolet** [comment]
Thanks @puredanger ! I'll update the doc.

**Comment by yokolet** [comment]
Done.

Thanks for the report, @daveliepmann !
