### ISSUE TITLE
As a contributor, I would like to submit pull requests instead of modifying the wiki directly

### ISSUE THREAD

**Issue by zspencer** [ClojureBridge/organizing#9]
I was poking around with [clojurebridge/curriculum#45](https://github.com/ClojureBridge/curriculum/issues/45) and started meandering into stuff that was more related to organizing a ClojureBridge than teaching/taing at a clojurebridge.

As I was about to move that into this repo, I realized that I would need to update the wiki, which has no peer-review process. 

I much prefer to submit changes through a peer-review process, as it:

1. Exposes a signal to other collaborators that content has been changed, allowing them to stay abreast of informational changes
2. Allows people with more experience than I to provide feedback to improve the documentation, instead of me making changes that may run contrary to the experiences and principles of ClojureBridge staff.
3. Integrates nicely with [Github's web-editor](https://github.com/blog/1945-quick-pull-requests)

**Comment by seancorfield** [comment]
I ran into this situation recently when I wanted to expand the Teacher Training material and wanted review and feedback before I made wholesale changes to the wiki.

I think this would be a good idea (to move the wiki into the repo itself - and then disable the wiki feature) but it's going to be a lot of busy work for someone who feels strongly enough to submit a PR to the repo with all that wiki content and all the links updated... And then we'll have to scour everywhere else to update current links that go to the wiki.

**Comment by davidchambers** [comment]
This is a terrific idea!
